### ISSUE TITLE
How to use the plugin when gif file without extension

### ISSUE THREAD

**Issue by acfasj** [pixijs/gif#10]
```ts
    use(resource: LoaderResource, next: (...args: any[]) => void): void
    {
        if (resource.extension === GIF_EXTENSION)
        {
            resource.animation = AnimatedGIF.fromBuffer(resource.data);
        }
        next();
    }
```
https://github.com/pixijs/gif/blob/425290bcf9f32fbabd7906c1697afc915f64d490/src/AnimatedGIFLoader.ts#L46

according to the source code, the plugin only works when resource extension is `.gif`,
while my gif url could be `https://example.com/425290bcf` without file extension

**Comment by q1998763** [comment]
![image](https://user-images.githubusercontent.com/14989849/182593040-994fff5f-bf78-4eec-a97e-ccce23fd654a.png)

**Comment by bigtimebuddy** [comment]
Thanks for the answer @q1998763. Closing this.
