### ISSUE TITLE
playback from percent of page loaded

### ISSUE THREAD

**Issue by locksy** [pixijs/gif#4]
I want to control the playback of a gif, where the frame corresponds to the percentage of the base page that is loaded.  In essence, a loading screen.  Is this possible?

**Comment by bigtimebuddy** [comment]
Yes, you can do something like this:

```js
gif.currentFrame = Math.round(percentage * (gif.totalFrames - 1));
```

Documentation has more information about properties: https://pixijs.io/gif/docs/PIXI.gif.AnimatedGIF.html
